/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dataSorter */

#ifndef _Included_dataSorter
#define _Included_dataSorter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dataSorter
 * Method:    insertionSort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_dataSorter_insertionSort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
